'use client';

import { useState } from 'react';
import { Plus, Pencil, MapPin, KeyRound, Eye } from 'lucide-react';
import { CmAccess } from '@/components/cm-access';
import { CmPushBadge, useCmPushStatus } from '@/components/cm-push-status';
import { SalonLocationField } from '@/components/salon-location';
import Link from 'next/link';
import { useStore } from '@/components/store';
import { Meter, Modal, MoneyField, shortDay } from '@/components/ui';
import { newId } from '@/lib/repository';
import { ars } from '@/lib/money';
import { cmPending, cmCoverageHistory } from '@/lib/domain';
import type { Cm, Salon } from '@/lib/types';

export default function Team(){
  const {db,update}=useStore(); const [edit,setEdit]=useState<Cm|null>(null); const [open,setOpen]=useState(false); const [error,setError]=useState('');
  const save=(e:React.FormEvent)=>{e.preventDefault();if(!edit)return;if(!edit.name.trim()){setError('Ingresá el nombre.');return}if(edit.usualFeeCents<0){setError('Revisá el honorario habitual.');return}const email=edit.email.trim().toLowerCase();if(email&&db.cms.some(x=>x.id!==edit.id&&x.email===email)){setError('Ese email ya lo tiene otra CM.');return}const clean={...edit,name:edit.name.trim(),email};update(db=>({...db,cms:db.cms.some(x=>x.id===clean.id)?db.cms.map(x=>x.id===clean.id?clean:x):[...db.cms,clean]}));setOpen(false);setEdit(null);setError('')};
  const pushStatus=useCmPushStatus();
  const [salon,setSalon]=useState<Salon|null>(null);const [access,setAccess]=useState<Cm|null>(null);
  const saveSalon=(e:React.FormEvent)=>{e.preventDefault();if(!salon)return;if(!salon.name.trim()){setError('Ingresá el nombre del salón.');return}const clean={...salon,name:salon.name.trim(),address:salon.address.trim()};update(db=>({...db,salons:db.salons.some(x=>x.id===clean.id)?db.salons.map(x=>x.id===clean.id?clean:x):[...db.salons,clean]}));setSalon(null);setError('')};
  const start=(cm?:Cm)=>{setEdit(cm?{...cm}:{id:newId(),name:'',phone:'',email:'',usualFeeCents:0,notes:''});setOpen(true)};
  return <div className="space-y-7"><div className="page-heading"><div><h1 className="page-title">Equipo</h1><p className="muted mt-2">Lo que se le debe a cada CM y sus próximas fiestas.</p></div><button className="btn btn-primary" onClick={()=>start()}><Plus size={19}/> Agregar CM</button></div><div className="team-list">{db.cms.map(cm=>{const history=cmCoverageHistory(db,cm.id);const total=history.reduce((s,h)=>s+h.totalCents,0);const paid=history.reduce((s,h)=>s+h.paidCents,0);const owed=cmPending(db,cm.id);const next=history.filter(h=>h.coverage.eventStatus==='pendiente'&&new Date(h.coverage.startsAt)>=new Date()).sort((a,b)=>a.coverage.startsAt.localeCompare(b.coverage.startsAt)).slice(0,3);return <section key={cm.id} className="card team-card" aria-labelledby={`cm-${cm.id}`}>
      <div className="team-top"><span className="team-avatar" aria-hidden="true">{cm.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div className="min-w-0 flex-1"><h2 id={`cm-${cm.id}`} className="text-lg font-extrabold">{cm.name}</h2><p className="muted text-sm">{cm.phone?<a className="underline-offset-4 hover:underline" href={`tel:${cm.phone.replace(/[^+0-9]/g,'')}`}>{cm.phone}</a>:'Sin teléfono'}</p><CmPushBadge status={pushStatus[cm.id]} firstName={cm.name.split(' ')[0]}/>{cm.notes&&<p className="muted mt-1 text-sm">{cm.notes}</p>}</div><div className="team-owed"><span>{owed>0?'Se le debe':'Al día'}</span><strong>{ars(owed)}</strong></div></div>
      {total>0&&<div className="mt-4"><Meter done={paid} total={total} label={`Pagado ${ars(paid)} de ${ars(total)}`}/><p className="muted mt-2 text-sm">Pagado {ars(paid)} de {ars(total)}</p></div>}
      <div className="mt-4">{next.length?<ul className="date-chips" aria-label="Próximas fiestas">{next.map(({coverage:c})=>{const d=shortDay(c.startsAt);return <li key={c.id}><Link href={`/coberturas/${c.id}`}><span className="chip-date"><strong>{d.day}</strong> {d.month}</span>{c.name}</Link></li>})}</ul>:<p className="muted text-sm">Sin fiestas asignadas por delante.</p>}</div>
      <div className="team-actions"><Link href={`/pagos?tab=pagos&cm=${cm.id}&action=registrar`} className="btn btn-secondary">Registrar pago</Link><button className="btn btn-quiet" onClick={()=>start(cm)}><Pencil size={16}/> Editar</button><button className="btn btn-quiet" onClick={()=>setAccess(cm)}><KeyRound size={16}/> Acceso</button><Link className="btn btn-quiet" href={`/equipo/${cm.id}/vista`}><Eye size={16}/> Ver como {cm.name.split(' ')[0]}</Link></div>
      <details className="team-history"><summary className="cursor-pointer font-bold">Historial de {history.length} {history.length===1?'cobertura':'coberturas'}</summary>{history.length?<ul className="ledger mt-3">{history.map(({coverage:c,totalCents,paidCents,pendingCents,hasReimbursements})=>{const d=shortDay(c.startsAt);return <li key={c.id}><Link href={`/coberturas/${c.id}`} className="ledger-row"><span className="ledger-date"><strong>{d.day}</strong>{d.month}</span><span className="min-w-0 flex-1"><span className="block font-bold">{c.name}</span><span className="muted block text-sm">{c.eventStatus==='cancelado'?'Cancelada, no suma al total':`Pagado ${ars(paidCents)} de ${ars(totalCents)}${hasReimbursements?', con reintegros':''}`}</span></span><span className="ledger-amount">{pendingCents>0?ars(pendingCents):'Saldada'}</span></Link></li>})}</ul>:<p className="muted mt-3 text-sm">Todavía no participó en coberturas.</p>}</details></section>})}</div>
    {db.cms.length===0&&<p className="muted">Todavía no cargaste a nadie del equipo. Agregá a cada CM con su honorario habitual.</p>}
    <section className="space-y-3 pt-4" aria-labelledby="salons-title"><div className="section-heading"><div><h2 id="salons-title" className="section-title">Salones</h2><p className="muted text-sm">Dónde se hacen las fiestas. Hace falta al menos uno para crear una cobertura.</p></div><button className="btn btn-secondary" onClick={()=>{setError('');setSalon({id:newId(),name:'',address:''})}}><Plus size={18}/> Agregar salón</button></div>
      {db.salons.length?<ul className="ledger card">{db.salons.map(x=><li key={x.id} className="ledger-row"><MapPin size={20} className="shrink-0 text-[var(--rosa)]"/><span className="min-w-0 flex-1"><span className="block font-bold">{x.name}</span><span className="muted block text-sm">{x.address||'Sin dirección'}</span><span className={`block text-sm ${x.lat!=null?'text-[var(--ok)]':'muted'}`}>{x.lat!=null?'Ubicación fijada: se puede pedir Uber':'Sin ubicación fijada'}</span></span><button className="btn btn-quiet btn-small" onClick={()=>{setError('');setSalon({...x})}}><Pencil size={15}/> Editar</button></li>)}</ul>:<p className="muted">Todavía no hay salones cargados.</p>}
    </section>
    {access&&<Modal title={`Acceso de ${access.name.split(' ')[0]}`} onClose={()=>setAccess(null)}><CmAccess cm={db.cms.find(x=>x.id===access.id)??access} onEdit={()=>{const cm=db.cms.find(x=>x.id===access.id)??access;setAccess(null);start(cm)}}/></Modal>}
    {salon&&<Modal title={db.salons.some(x=>x.id===salon.id)?'Editar salón':'Agregar salón'} onClose={()=>{setSalon(null);setError('')}}><form onSubmit={saveSalon} className="space-y-4"><label className="block"><span className="label">Nombre *</span><input className="field" value={salon.name} onChange={e=>setSalon({...salon,name:e.target.value})} placeholder="Ej. Eclipse" required/></label><label className="block"><span className="label">Dirección</span><input className="field" value={salon.address} onChange={e=>setSalon({...salon,address:e.target.value})}/></label><SalonLocationField address={salon.address} coords={salon.lat!=null&&salon.lng!=null?{lat:salon.lat,lng:salon.lng}:null} onChange={c=>setSalon(c?{...salon,lat:c.lat,lng:c.lng}:{...salon,lat:undefined,lng:undefined})}/>{error&&<p role="alert" className="field-error">{error}</p>}<button type="submit" className="btn btn-primary w-full">Guardar salón</button></form></Modal>}
    {open&&edit&&<Modal title={db.cms.some(x=>x.id===edit.id)?'Editar CM':'Agregar CM'} onClose={()=>{setOpen(false);setError('')}}><form onSubmit={save} className="space-y-4"><label><span className="label">Nombre *</span><input className="field" value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})} required/></label><label><span className="label">Teléfono</span><input className="field" type="tel" value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label><MoneyField label="Honorario habitual" value={edit.usualFeeCents} onChange={v=>setEdit({...edit,usualFeeCents:v})} hint="Se completa solo al asignarla a una fiesta. Después se puede cambiar en cada una."/><label className="block"><span className="label">Email</span><input className="field" type="email" autoComplete="off" value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/><span className="muted mt-2 block text-sm">Con este email entra a ver sus fechas y sus pagos.</span></label><label><span className="label">Notas</span><textarea className="field" value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>{error&&<p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}<button type="submit" className="btn btn-primary w-full">Guardar CM</button></form></Modal>}
  </div>;
}


